# Lain Wired i3
background = #030403
foreground = #c8c2aa
cursor-color = #e7dec8
cursor-text = #030403
selection-background = #0d1722
selection-foreground = #8fb6dd

palette = 0=#090a08
palette = 1=#c94f37
palette = 2=#8ba36f
palette = 3=#d0a85a
palette = 4=#6f9ed0
palette = 5=#b58ad6
palette = 6=#76b7a8
palette = 7=#c8c2aa
palette = 8=#343832
palette = 9=#d1624f
palette = 10=#a6b98a
palette = 11=#e6c06f
palette = 12=#8fb6dd
palette = 13=#c79ee6
palette = 14=#9bd8ca
palette = 15=#e7dec8
