$color = rgba(5, 5, 5, 1.0)
$inner_color = rgba(5, 5, 5, 0.84)
$outer_color = rgba(255, 49, 49, 1.0)
$font_color = rgba(255, 255, 255, 1.0)
$placeholder_color = rgba(215, 215, 215, 0.72)
$check_color = rgba(255, 49, 49, 1.0)
