# Lain Wired i3
foreground              #c8c2aa
background              #030403
selection_foreground    #8fb6dd
selection_background    #0d1722
cursor                  #e7dec8
cursor_text_color       #030403

color0  #090a08
color1  #c94f37
color2  #8ba36f
color3  #d0a85a
color4  #6f9ed0
color5  #b58ad6
color6  #76b7a8
color7  #c8c2aa
color8  #343832
color9  #d1624f
color10 #a6b98a
color11 #e6c06f
color12 #8fb6dd
color13 #c79ee6
color14 #9bd8ca
color15 #e7dec8
