set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:RGB"
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g status-position bottom
set -g status-interval 2
set -g status-justify left
set -g escape-time 0
set -g mouse on

set -g mode-style "fg=#8fb6dd,bg=#0d1722,bold"
set -g message-style "fg=#8fb6dd,bg=#0d1722,bold"
set -g pane-border-style "fg=#343832"
set -g pane-active-border-style "fg=#6f9ed0"
set -g status-style "fg=#c8c2aa,bg=#030403"
set -g status-left "#[fg=#030403,bg=#6f9ed0,bold] #S #[fg=#6f9ed0,bg=#030403] "
set -g status-right "#[fg=#625f55]%Y-%m-%d #[fg=#e7dec8]%H:%M "
set -g window-status-format "#[fg=#625f55] #I:#W "
set -g window-status-current-format "#[fg=#8fb6dd,bg=#0d1722,bold] #I:#W "
set -g window-status-separator ""

bind r source-file ~/.config/tmux/tmux.conf \; display "tmux reloaded"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5
bind ? display-popup -E -w 80% -h 70% -T "tmux keys" "omarchy-menu-tmux-keybindings --print | less -R"
